apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort: 80
      #definir intervale de portas
      nodePort: 30000
  selector:
    app: primeiro-pod
#fazer o bind de um service par um pod
# no caso vou utilizar o pod-1