apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: portal-noticias-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: portal-noticias-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource # Tipo de metrica
      resource: # Recurso a ser monitorado
        name: cpu # Nome do recurso
        target:
          type: Utilization # Tipo de metrica
          averageUtilization: 50 # Média de utilização do recurso em %
